export const bottomBar: string;
export const takeawayBlue: string;
export const takeawayGrey: string;
export const searchBlue: string;
export const searchGrey: string;
export const orderBlue: string;
export const orderGrey: string;
export const userBlue: string;
export const userGrey: string;
