export const shopBanner: string;
export const mask: string;
export const bg: string;
export const backIcon: string;
export const shop: string;
export const shopImg: string;
export const shopMes: string;
export const shopDetail: string;
export const shopActivity: string;
